### ISSUE TITLE
Instances are giving error on every start

### ISSUE THREAD

**Issue by 32sy** [Ponywka/MultiMC5-with-offline#8]
### Description of bug

then i'm launched a instance, it show this error:
_Exception in thread "main" java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:171)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)_

### Steps to reproduce

Just try to launch instance

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by gazelleguardian** [comment]
Well it says that at the top:

`net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

You are trying to launch minecraft with an (older) unsupported version of java.
If you are trying to launch one of the newer releases of minecraft you need to install Java 17.

Go to https://docs.microsoft.com/en-us/java/openjdk/download and download and install the "msi" version. After that you need point MultiMC in Options->Java->Java path to the intallation folder of the version you downloaded (i think it's usually found in C:\Program Files\OpenJDK\jdk-17.0.1\bin\javaw.exe )

Note that you cannot use the newer version of Java that you just installed to run older minecraft releases. So if you set Java 17 as default for the application you will have to change the Java version to the older Java 8 when you are running older instances.
To change Java version on a per instance basis:
- Select the instance
- In the right column menu select "Instance settings"
- The go to Settings->Java Installation and change it to Java 1.8

**Comment by Ponywka** [comment]
It is not a bug. As the @gazelleguardian above wrote - just update Java to version 17
